// <auto-generated />
using System;
using Lodgify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lodgify.Migrations
{
    [DbContext(typeof(cookiesContext))]
    [Migration("20220206091323_AddingCookieOrderPropertyInOrderDetailsClass")]
    partial class AddingCookieOrderPropertyInOrderDetailsClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lodgify.Models.CookieOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("CookieOrder");
                });

            modelBuilder.Entity("Lodgify.Models.CookieType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CookieType");
                });

            modelBuilder.Entity("Lodgify.Models.CookieTypePriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AtDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CookieTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CookieTypeId");

                    b.ToTable("CookieTypePriceList");
                });

            modelBuilder.Entity("Lodgify.Models.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CookieOrderId")
                        .HasColumnType("int");

                    b.Property<int>("CookieTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CookieOrderId");

                    b.HasIndex("CookieTypeId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Lodgify.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Lodgify.Models.CookieOrder", b =>
                {
                    b.HasOne("Lodgify.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Lodgify.Models.CookieTypePriceList", b =>
                {
                    b.HasOne("Lodgify.Models.CookieType", null)
                        .WithMany("Items")
                        .HasForeignKey("CookieTypeId");
                });

            modelBuilder.Entity("Lodgify.Models.OrderDetails", b =>
                {
                    b.HasOne("Lodgify.Models.CookieOrder", "CookieOrder")
                        .WithMany("Items")
                        .HasForeignKey("CookieOrderId");

                    b.HasOne("Lodgify.Models.CookieType", "CookieType")
                        .WithMany()
                        .HasForeignKey("CookieTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CookieOrder");

                    b.Navigation("CookieType");
                });

            modelBuilder.Entity("Lodgify.Models.CookieOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Lodgify.Models.CookieType", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
